### PR TITLE
Adds ...ToString() methods for each enum

### PR DESCRIPTION
**Pull request by gmabey**
Addresses #216

### CODE REVIEW

**Comment by semlanik** [comment]
Hi @gmabey , thank you for the contribution! Overall it looks good to me, but I think it could be implemented using QDataStream operator()<<, as Qt does. Also, I think this approach also will fix the displaying enums in QML.

**Comment by gmabey** [comment]
> Hi @gmabey , thank you for the contribution! Overall it looks good to me, but I think it could be implemented using QDataStream operator()<<, as Qt does. Also, I think this approach will fix the displaying enums in QML.

@semlanik I'm afraid I need you to give me a little bit more detail on the approach you'd like to see.  Is there some other example (in Qt somewhere?) that implements what you hope to see?

**Comment by semlanik** [comment]
Ok, after reevaluation of this feature I found the common solution, that actually doesn't require (manual)generating of any extra code at all:
```cpp
<any place in the users code>
...
template<typename T,
         typename std::enable_if_t<std::is_enum<T>::value, int> = 0>
QString enumToString(T v) {
    return QVariant::fromValue(v).toString();
}
...
```

Also, looks like that it should not be a protobuf functionality, but should be implemented by project it self.

**Comment by gmabey** [comment]
Ok great I like it!

**Pull request closed without merging**
